export const wikidataPrefixes = {
  /* Notice that the order is important to match first the longest prefixes */
  bd: "http://www.bigdata.com/rdf#",
  cc: "http://creativecommons.org/ns#",
  dct: "http://purl.org/dc/terms/",
  geo: "http://www.opengis.net/ont/geosparql#",
  hint: "http://www.bigdata.com/queryHints#",
  ontolex: "http://www.w3.org/ns/lemon/ontolex#",
  owl: "http://www.w3.org/2002/07/owl#",
  prn: "http://www.wikidata.org/prop/reference/value-normalized/",
  prv: "http://www.wikidata.org/prop/reference/value/",
  pqn: "http://www.wikidata.org/prop/qualifier/value-normalized/",
  pqv: "http://www.wikidata.org/prop/qualifier/value/",
  pq: "http://www.wikidata.org/prop/qualifier/",
  pr: "http://www.wikidata.org/prop/reference/",
  prov: "http://www.w3.org/ns/prov#",
  psn: "http://www.wikidata.org/prop/statement/value-normalized/",
  psv: "http://www.wikidata.org/prop/statement/value/",
  ps: "http://www.wikidata.org/prop/statement/",
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
  rdfs: "http://www.w3.org/2000/01/rdf-schema#",
  schema: "http://schema.org/",
  skos: "http://www.w3.org/2004/02/skos/core#",
  wikibase: "http://wikiba.se/ontology#",
  wdata: "http://www.wikidata.org/wiki/Special:EntityData/",
  wdno: "http://www.wikidata.org/prop/novalue/",
  wdref: "http://www.wikidata.org/reference/",
  wds: "http://www.wikidata.org/entity/statement/",
  wdt: "http://www.wikidata.org/prop/direct/",
  wdtn: "http://www.wikidata.org/prop/direct-normalized/",
  wdv: "http://www.wikidata.org/value/",
  wd: "http://www.wikidata.org/entity/",
  xsd: "http://www.w3.org/2001/XMLSchema#",
  p: "http://www.wikidata.org/prop/",
};
